spring:
  application:
    name: kudaGoAPI
  jackson:
    time-zone: UTC
  profiles:
# could be: reactor or future
    active: reactor
  datasource:
    url: jdbc:postgresql://localhost:5433/fintech
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
  liquibase:
    change-log: static/migrations/db.changelog-master.yml

server:
  port: 8090

app:
  location-base-url: https://kudago.com/public-api/v1.4/locations/?fields=slug,timezone,language,name
  category-base-url: https://kudago.com/public-api/v1.4/place-categories
  events-base-url:  https://kudago.com/public-api/v1.4/events/?fields=price,is_free,title,description,site_url&order_by=favorites_count
  currency-base-url: http://localhost:8080/currencies/convert
  fixed-thread-pool-size: 2
  duration: 3600
  max-requests: 10

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
